rm(list = ls())

library(rdbnomics)
library(tidyverse)

#Data of GDP
gdp_world_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-1W')%>% filter(!is.na(value))
gdp_arabworld_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-1A')%>% filter(!is.na(value))
gdp_argentina_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-AR')%>% filter(!is.na(value))
gdp_australia_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-AU')%>% filter(!is.na(value))
gdp_belgium_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-BE')%>% filter(!is.na(value))
gdp_brazil_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-BR')%>% filter(!is.na(value))
gdp_bulgaria_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-BG')%>% filter(!is.na(value))
gdp_canada_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-CA')%>% filter(!is.na(value))
gdp_centralAfri_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-CF')%>% filter(!is.na(value))
gdp_chile_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-CL')%>% filter(!is.na(value))
gdp_china_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-CN')%>% filter(!is.na(value))
gdp_france_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-FR')%>% filter(!is.na(value))
gdp_germany_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-DE')%>% filter(!is.na(value))
gdp_greece_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-GR')%>% filter(!is.na(value))
gdp_india_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-IN')%>% filter(!is.na(value))
gdp_iran_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-IR')%>% filter(!is.na(value))
gdp_iraq_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-IQ')%>% filter(!is.na(value))
gdp_israel_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-IL')%>% filter(!is.na(value))
gdp_italy_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-IT')%>% filter(!is.na(value))
gdp_japan_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-JP')%>% filter(!is.na(value))
gdp_korea_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-KR')%>% filter(!is.na(value))
gdp_malaysia_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-MY')%>% filter(!is.na(value))
gdp_netherlands_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-NL')%>% filter(!is.na(value))
gdp_newzealand_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-NZ')%>% filter(!is.na(value))
gdp_norway_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-NO')%>% filter(!is.na(value))
gdp_pakistan_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-PK')%>% filter(!is.na(value))
gdp_poland_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-PL')%>% filter(!is.na(value))
gdp_portugal_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-PT')%>% filter(!is.na(value))
gdp_romania_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-RO')%>% filter(!is.na(value))
gdp_russian_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-RU')%>% filter(!is.na(value))
gdp_saudiArabia_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-SA')%>% filter(!is.na(value))
gdp_singapore_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-SG')%>% filter(!is.na(value))
gdp_southAfri_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-ZA')%>% filter(!is.na(value))
gdp_spain_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-ES')%>% filter(!is.na(value))
gdp_sweden_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-SE')%>% filter(!is.na(value))
gdp_switzerland_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-CH')%>% filter(!is.na(value))
gdp_thailand_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-TH')%>% filter(!is.na(value))
gdp_turkey_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-TR')%>% filter(!is.na(value))
gdp_ukraine_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-UA')%>% filter(!is.na(value))
gdp_unitedKingdom_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-GB')%>% filter(!is.na(value))
gdp_unitedStates_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-US')%>% filter(!is.na(value))
gdp_vietnam_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD-VN')%>% filter(!is.na(value))

#Data of GDP per capita
gdppc_world_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-1W')%>% filter(!is.na(value))
gdppc_arabworld_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-1A')%>% filter(!is.na(value))
gdppc_argentina_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-AR')%>% filter(!is.na(value))
gdppc_australia_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-AU')%>% filter(!is.na(value))
gdppc_belgium_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-BE')%>% filter(!is.na(value))
gdppc_brazil_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-BR')%>% filter(!is.na(value))
gdppc_bulgaria_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-BG')%>% filter(!is.na(value))
gdppc_canada_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-CA')%>% filter(!is.na(value))
gdppc_centralAfri_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-CF')%>% filter(!is.na(value))
gdppc_chile_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-CL')%>% filter(!is.na(value))
gdppc_china_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-CN')%>% filter(!is.na(value))
gdppc_france_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-FR')%>% filter(!is.na(value))
gdppc_germany_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-DE')%>% filter(!is.na(value))
gdppc_greece_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-GR')%>% filter(!is.na(value))
gdppc_india_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-IN')%>% filter(!is.na(value))
gdppc_iran_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-IR')%>% filter(!is.na(value))
gdppc_iraq_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-IQ')%>% filter(!is.na(value))
gdppc_israel_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-IL')%>% filter(!is.na(value))
gdppc_italy_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-IT')%>% filter(!is.na(value))
gdppc_japan_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-JP')%>% filter(!is.na(value))
gdppc_korea_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-KR')%>% filter(!is.na(value))
gdppc_malaysia_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-MY')%>% filter(!is.na(value))
gdppc_netherlands_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-NL')%>% filter(!is.na(value))
gdppc_newzealand_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-NZ')%>% filter(!is.na(value))
gdppc_norway_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-NO')%>% filter(!is.na(value))
gdppc_pakistan_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-PK')%>% filter(!is.na(value))
gdppc_poland_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-PL')%>% filter(!is.na(value))
gdppc_portugal_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-PT')%>% filter(!is.na(value))
gdppc_romania_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-RO')%>% filter(!is.na(value))
gdppc_russian_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-RU')%>% filter(!is.na(value))
gdppc_saudiArabia_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-SA')%>% filter(!is.na(value))
gdppc_singapore_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-SG')%>% filter(!is.na(value))
gdppc_southAfri_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-ZA')%>% filter(!is.na(value))
gdppc_spain_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-ES')%>% filter(!is.na(value))
gdppc_sweden_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-SE')%>% filter(!is.na(value))
gdppc_switzerland_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-CH')%>% filter(!is.na(value))
gdppc_thailand_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-TH')%>% filter(!is.na(value))
gdppc_turkey_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-TR')%>% filter(!is.na(value))
gdppc_ukraine_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-UA')%>% filter(!is.na(value))
gdppc_unitedKingdom_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-GB')%>% filter(!is.na(value))
gdppc_unitedStates_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-US')%>% filter(!is.na(value))
gdppc_vietnam_2010US <- rdb(ids = 'WB/WDI/NY.GDP.PCAP.KD-VN')%>% filter(!is.na(value))

#Data of GDP growth
gdpgrwth_world_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-1W')%>% filter(!is.na(value))
gdpgrwth_arabworld_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-1A')%>% filter(!is.na(value))
gdpgrwth_argentina_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-AR')%>% filter(!is.na(value))
gdpgrwth_australia_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-AU')%>% filter(!is.na(value))
gdpgrwth_belgium_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-BE')%>% filter(!is.na(value))
gdpgrwth_brazil_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-BR')%>% filter(!is.na(value))
gdpgrwth_bulgaria_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-BG')%>% filter(!is.na(value))
gdpgrwth_canada_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-CA')%>% filter(!is.na(value))
gdpgrwth_centralAfri_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-CF')%>% filter(!is.na(value))
gdpgrwth_chile_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-CL')%>% filter(!is.na(value))
gdpgrwth_china_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-CN')%>% filter(!is.na(value))
gdpgrwth_france_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-FR')%>% filter(!is.na(value))
gdpgrwth_germany_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-DE')%>% filter(!is.na(value))
gdpgrwth_greece_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-GR')%>% filter(!is.na(value))
gdpgrwth_india_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-IN')%>% filter(!is.na(value))
gdpgrwth_iran_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-IR')%>% filter(!is.na(value))
gdpgrwth_iraq_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-IQ')%>% filter(!is.na(value))
gdpgrwth_israel_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-IL')%>% filter(!is.na(value))
gdpgrwth_italy_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-IT')%>% filter(!is.na(value))
gdpgrwth_japan_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-JP')%>% filter(!is.na(value))
gdpgrwth_korea_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-KR')%>% filter(!is.na(value))
gdpgrwth_malaysia_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-MY')%>% filter(!is.na(value))
gdpgrwth_netherlands_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-NL')%>% filter(!is.na(value))
gdpgrwth_newzealand_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-NZ')%>% filter(!is.na(value))
gdpgrwth_norway_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-NO')%>% filter(!is.na(value))
gdpgrwth_pakistan_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-PK')%>% filter(!is.na(value))
gdpgrwth_poland_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-PL')%>% filter(!is.na(value))
gdpgrwth_portugal_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-PT')%>% filter(!is.na(value))
gdpgrwth_romania_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-RO')%>% filter(!is.na(value))
gdpgrwth_russian_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-RU')%>% filter(!is.na(value))
gdpgrwth_saudiArabia_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-SA')%>% filter(!is.na(value))
gdpgrwth_singapore_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-SG')%>% filter(!is.na(value))
gdpgrwth_southAfri_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-ZA')%>% filter(!is.na(value))
gdpgrwth_spain_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-ES')%>% filter(!is.na(value))
gdpgrwth_sweden_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-SE')%>% filter(!is.na(value))
gdpgrwth_switzerland_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-CH')%>% filter(!is.na(value))
gdpgrwth_thailand_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-TH')%>% filter(!is.na(value))
gdpgrwth_turkey_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-TR')%>% filter(!is.na(value))
gdpgrwth_ukraine_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-UA')%>% filter(!is.na(value))
gdpgrwth_unitedKingdom_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-GB')%>% filter(!is.na(value))
gdpgrwth_unitedStates_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-US')%>% filter(!is.na(value))
gdpgrwth_vietnam_2010US <- rdb(ids = 'WB/WDI/NY.GDP.MKTP.KD.ZG-VN')%>% filter(!is.na(value))

#Data of CO2emission
co2emission_world <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-1W')%>% filter(!is.na(value))
co2emission_arabworld <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-1A')%>% filter(!is.na(value))
co2emission_argentina <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-AR')%>% filter(!is.na(value))
co2emission_australia <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-AU')%>% filter(!is.na(value))
co2emission_belgium <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-BE')%>% filter(!is.na(value))
co2emission_brazil <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-BR')%>% filter(!is.na(value))
co2emission_bulgaria <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-BG')%>% filter(!is.na(value))
co2emission_canada <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-CA')%>% filter(!is.na(value))
co2emission_centralAfri <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-CF')%>% filter(!is.na(value))
co2emission_chile <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-CL')%>% filter(!is.na(value))
co2emission_china <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-CN')%>% filter(!is.na(value))
co2emission_france <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-FR')%>% filter(!is.na(value))
co2emission_germany <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-DE')%>% filter(!is.na(value))
co2emission_greece <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-GR')%>% filter(!is.na(value))
co2emission_india <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-IN')%>% filter(!is.na(value))
co2emission_iran <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-IR')%>% filter(!is.na(value))
co2emission_iraq <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-IQ')%>% filter(!is.na(value))
co2emission_israel <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-IL')%>% filter(!is.na(value))
co2emission_italy <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-IT')%>% filter(!is.na(value))
co2emission_japan <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-JP')%>% filter(!is.na(value))
co2emission_korea <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-KR')%>% filter(!is.na(value))
co2emission_malaysia <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-MY')%>% filter(!is.na(value))
co2emission_netherlands <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-NL')%>% filter(!is.na(value))
co2emission_newzealand <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-NZ')%>% filter(!is.na(value))
co2emission_norway <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-NO')%>% filter(!is.na(value))
co2emission_pakistan <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-PK')%>% filter(!is.na(value))
co2emission_poland <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-PL')%>% filter(!is.na(value))
co2emission_portugal <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-PT')%>% filter(!is.na(value))
co2emission_romania <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-RO')%>% filter(!is.na(value))
co2emission_russian <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-RU')%>% filter(!is.na(value))
co2emission_saudiArabia <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-SA')%>% filter(!is.na(value))
co2emission_singapore <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-SG')%>% filter(!is.na(value))
co2emission_southAfri <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-ZA')%>% filter(!is.na(value))
co2emission_spain <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-ES')%>% filter(!is.na(value))
co2emission_sweden <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-SE')%>% filter(!is.na(value))
co2emission_switzerland <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-CH')%>% filter(!is.na(value))
co2emission_thailand <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-TH')%>% filter(!is.na(value))
co2emission_turkey <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-TR')%>% filter(!is.na(value))
co2emission_ukraine <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-UA')%>% filter(!is.na(value))
co2emission_unitedKingdom <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-GB')%>% filter(!is.na(value))
co2emission_unitedStates <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-US')%>% filter(!is.na(value))
co2emission_vietnam <- rdb(ids = 'WB/WDI/EN.ATM.CO2E.KD.GD-VN')%>% filter(!is.na(value))

#Append all the dataframes with the same name pattern
gdp <- mget(ls(pattern="^gdp\\_.")) %>%
  bind_rows()
gdppercap <- mget(ls(pattern="^gdppc\\_.")) %>%
  bind_rows()
gdpgrowth <- mget(ls(pattern="^gdpgrwth\\_.")) %>%
  bind_rows()
co2emission <- mget(ls(pattern="^co2emission\\_.")) %>%
  bind_rows()

#Seperate column into columns containing series name and country
gdp <- gdp%>%separate(series_name,c("series_name","region"),sep = " – ")
gdppercap <- gdppercap%>%separate(series_name,c("series_name","region"),sep = " – ")
gdpgrowth <- gdpgrowth%>%separate(series_name,c("series_name","region"),sep = " – ")
co2emission <- co2emission%>%separate(series_name,c("series_name","region"),sep = " – ")

#Merge tables according to the year variable and the region variable
co2emission_values <- data.frame(original_period = co2emission$original_period, region = co2emission$region, co2emissionval = co2emission$value)
gdp_emission <- merge(x=gdp,y=co2emission_values,by=c("original_period","region"),all.x = TRUE)
gdppercap_emission <- merge(x=gdppercap,y=co2emission_values,by=c("original_period","region"),all.x = TRUE)
gdpgrowth_emission <- merge(x=gdpgrowth,y=co2emission_values,by=c("original_period","region"),all.x = TRUE)

gdp_emission <-data.frame(original_period = gdp_emission$original_period, region = gdp_emission$region, gdpval = gdp_emission$value, co2emissionval = gdp_emission$co2emissionval)
gdppercap_emission <-data.frame(original_period = gdppercap_emission$original_period, region = gdppercap_emission$region, gdppercapval = gdppercap_emission$value, co2emissionval = gdppercap_emission$co2emissionval)
gdpgrowth_emission <-data.frame(original_period = gdpgrowth_emission$original_period, region = gdpgrowth_emission$region, gdpgrowthval = gdpgrowth_emission$value, co2emissionval = gdpgrowth_emission$co2emissionval)

data_final <- merge(x=gdp_emission,y=gdppercap_emission,by=c("original_period","region"),all.x = TRUE)%>%merge(y=gdpgrowth_emission,by=c("original_period","region"),all.x = TRUE)
data_final <- data_final[,c("original_period","region","gdpval","gdppercapval","gdpgrowthval","co2emissionval.x")]



